### ISSUE TITLE
Silent crash on wrong login detail

### ISSUE THREAD

**Issue by Steinsplitter** [Commonists/Up#2]
Seems broken, after login the window is hiding. No error output.

**Comment by maflcko** [comment]
Happens when you type in the wrong login details.

.. Exception handling in Fastily's code does not comply with best practices.

**Comment by Steinsplitter** [comment]
> Happens when you type in the wrong login details.

I haven't typed the wrong login details. It still broken for me.

**Comment by Steinsplitter** [comment]
uh, never mind.   downloaded the wrong release :(
